### PR TITLE
Add option for hiding the swatchView

### PR DESCRIPTION
**Pull request by JulianEggers**
Hi Martin,
I really like your color picker and would like to use it for two little projects that I am currently working on.  However, the color picker would fit much better into my apps without the swatchView.
That is why I created this pull request that hopefully implements the complete functionality + readme documentation to hide the swatchView. 

I hope this functionality is fine for you.
-- Julian

### CODE REVIEW

**Comment by martin-stone** [comment]
Looks great! Just one tiny oversight: The ColorPreference class doesn't do anything with the showPreview variable that you set -- Just needs a `picker.showPreview(showPreview);` in `onPrepareDialogBuilder()`. Will gladly merge it once added.

**Comment by JulianEggers** [comment]
Added the missing line.
Thank you in advance. :)

**Comment by martin-stone** [comment]
Great stuff -- Merged!

I'll get a version up onto jcenter shortly.

**Comment by martin-stone** [comment]
It's now up on jcenter, version 2.2.0.

Thanks!

**Pull request merged**
